name: artauct_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animations: ^2.0.11
  gradient_borders: ^1.0.1
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1  
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true  
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/